<a href="https://colab.research.google.com/github/nobottle/deeplearning_pratice/blob/main/%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# 새 섹션

In [ ]:
import os
from google.colab import drive
drive.mount('/content/drive/')


In [ ]:
data=torch.randn(2,3) #randn은 매트릭스를 만드는 형태 (2,3)형태로 만든다 여기서는 
#gaussian distribution평균0 분산1인 분포에서 랜덤하게 샘플링하겟다

In [ ]:

data=torch.rand(2,3) #위에랑 같은 거
#uniform distribution에서 [0,1]에서 샘플링하겟다

In [ ]:
print(data)

tensor([[0.5109, 0.9707, 0.2569],
        [0.2004, 0.2633, 0.1888]])


In [ ]:
print(data)
print(data*5)
print(data+data)
print(data.shape) #shape모양,형태를 보여줌
print(data.dtype)#value들의 dtype을 나타내준다

tensor([[0.5109, 0.9707, 0.2569],
        [0.2004, 0.2633, 0.1888]])
tensor([[2.5544, 4.8535, 1.2844],
        [1.0018, 1.3166, 0.9442]])
tensor([[1.0218, 1.9414, 0.5138],
        [0.4007, 0.5267, 0.3777]])
torch.Size([2, 3])
torch.float32


**data를 생성하는 여러 방법!

In [ ]:
data=torch.zeros([2,4])
print(data)
data=torch.ones([2,4])
print(data)
data=torch.eye(4)
print(data)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


list와 차이점 및 벡터 내적 #그냥 리스트와 tensor로변경 후 연산 차이

In [ ]:
lst1=[1,2] 
lst2=[3,4]
tor1=torch.tensor([1,2])
tor2=torch.tensor([3,4])
print(lst1+lst2)
print(tor1+tor2)
print(tor1*tor2)

print(sum(tor1+tor2)) #[4,6]의 합
print(tor1.dot(tor2)) # 1*3+2*4=11
print(torch.dot(tor1,tor2))
print(torch.matmul(tor1,tor2)) 
print(torch.matmul(tor1.view(1,-1),tor2)[0]) #view함수 mataul은 shape이 매칭이 되어야하지만 위에는 안맞음 맞추기위해서 사용

[1, 2, 3, 4]
tensor([4, 6])
tensor([3, 8])
tensor(10)
tensor(11)
tensor(11)
tensor(11)
tensor(11)


매트릭스의 곱

'''
그래요, 행렬 곱셈의 결과의 모양은 곱셈 되는 행렬의 모양에 따라 달라집니다. 구체적으로, 모양이 (m, n)인 행렬 A와 모양이 (n, p)인 행렬 B가 있을 때, 결과 행렬 C의 모양은 (m, p)이 됩니다.

A의 열 수와 B의 행 수가 같아야 곱셈이 유효합니다. 결과 행렬 C는 A의 행 수에 해당하는 m 행과 B의 열 수에 해당하는 p 열을 갖습니다.

PyTorch에서는 matmul 함수 또는 @ 연산자를 사용하여 행렬 곱셈을 수행할 수 있습니다. 결과는 입력 행렬의 모양에 따라 예상된 모양이 됩니다. *이탤릭체 텍스트*

In [ ]:
mat1=torch.tensor([[2,5,8],[5,3,1]]) #shape은 (2,3)
mat2=torch.tensor([[3,2],[5,4],[7,8]]) #shape은(3,2)
print(mat1)
print(mat2)
print(torch.matmul(mat1,mat2)) #결과는 matrix (2,2)형태로 나옴
print(torch.matmul(mat2,mat1)) #(3,3)이 나올것

tensor([[2, 5, 8],
        [5, 3, 1]])
tensor([[3, 2],
        [5, 4],
        [7, 8]])
tensor([[87, 88],
        [37, 30]])
tensor([[16, 21, 26],
        [30, 37, 44],
        [54, 59, 64]])


인덱싱/슬라이딩

In [ ]:
data=torch.randn(4,3)
print(data)
print(data[2,:]) #low vector
print(data[:,1]) #col vector
print(data[2][1]) #matrix A의 (2,1)의 값

tensor([[-0.8339,  0.3977, -0.8879],
        [ 0.0668, -0.1108, -0.4417],
        [-0.9070, -0.6817, -0.0522],
        [ 0.1541,  1.4863, -0.1358]])
tensor([-0.9070, -0.6817, -0.0522])
tensor([ 0.3977, -0.1108, -0.6817,  1.4863])
tensor(-0.6817)


기본적인 통계 관련 함수

In [ ]:
print(torch.sum(data))
print(torch.mean(data)) #평균
print(torch.var(data))#분산
print(torch.std(data))#표준편차
print()
#scalar value에 대해서 tensor속의 값만 추출
print(torch.sum(data).item())#item
print(torch.mean(data).item())
print(torch.var(data).item())
print(torch.std(data).item())

tensor(-1.9462)
tensor(-0.1622)
tensor(0.4618)
tensor(0.6796)

-1.9462189674377441
-0.1621849089860916
0.46179792284965515
0.6795571446418762


pytorch조건문

In [ ]:
print(torch.where(data>0,torch.ones(data.shape),torch.zeros(data.shape)))
#where >>조건문 data가 0보다 크면 1을 채우고 아니면 0을 채워라

tensor([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 0.],
        [1., 1., 0.]])


Numpy와 호환

In [ ]:
import numpy

In [ ]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)
a=torch.from_numpy(b)
print(a)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


GPU의 사용

In [ ]:
print(torch.cuda.is_available())
print(torch.cuda.device_count())
#디바이스가 연결되어 잇다면

#True
#1
#의 결괏값이 나온다

True
1


In [ ]:
x=torch.tensor([1,1]).cuda()
print(x)
x=x.cpu()
print(x)

tensor([1, 1], device='cuda:0')
tensor([1, 1])


In [ ]:
x=torch.tensor([1.,1.]).cuda()
y=torch.tesor([0.5,0.1])
#이거는 연산이 되지 않음 x는 cuda >>gpu에 잇고 y는 cpu에 잇으므로

In [ ]:
from math import e
#computational graph

'''
requires_grad"는 PyTorch에서 텐서의 기울기를 계산하는지 여부를 지정하는 플래그입니다. 
#기울기 계산이 필요한 텐서에서는 requires_grad=True로 지정해줘야 합니다.
 만약 requires_grad=False로 지정하면, 기울기 계산이 필요없는 텐서로 처리되며, 연산에서의 메모리 절약이 가능합니다.
'''
a=torch.tensor([2.],requires_grad=True)
b=torch.tensor([1.],requires_grad=True)
c=a+b
d=b+1
e=c*d
print(a)
print(b)
print(c)
print(d)
print(e) #마지막 노드!!

tensor([2.], requires_grad=True)
tensor([1.], requires_grad=True)
tensor([3.], grad_fn=<AddBackward0>)
tensor([2.], grad_fn=<AddBackward0>)
tensor([6.], grad_fn=<MulBackward0>)


In [ ]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([2.])
None
None


In [ ]:
from math import e
#computational graph

'''
requires_grad"는 PyTorch에서 텐서의 기울기를 계산하는지 여부를 지정하는 플래그입니다. 
#기울기 계산이 필요한 텐서에서는 requires_grad=True로 지정해줘야 합니다.
 만약 requires_grad=False로 지정하면, 기울기 계산이 필요없는 텐서로 처리되며, 연산에서의 메모리 절약이 가능합니다.
'''
a=torch.tensor([2.],requires_grad=True)
b=torch.tensor([1.],requires_grad=True)
c=a+b
d=b+1
e=c*d
c.retain_grad()
d.retain_grad()
e.retain_grad()

In [ ]:
e.backward(retain_graph=True)

In [ ]:

print(a.grad)
print(b.grad)
print(c.grad)
print(d.grad)
print(e.grad)


tensor([2.])
tensor([5.])
tensor([2.])
tensor([3.])
tensor([1.])


In [ ]:
a.grad.zero_() #값을 0으로 초기화시킴
print(a.grad)

tensor([0.])
